amazonProperties:
  endpointUrl: https://s3.ap-northeast-2.amazonaws.com
  accessKey: AKIAXX3U5WEPBAMJKM64
  secretKey: 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
  bucketName: busking-land
  regionName: ap-northeast-2




